In [1]:
import helpy
import pandas as pd

In [2]:
analysis_df = helpy.get_analysis_df(.12, 100)

In [3]:
helpy.predict_residuals(analysis_df)

In [4]:
rf, pred = helpy.create_random_forest(analysis_df)

MAE:  12.203
RMSE: 15.296
R²:   0.249

In [5]:
rf, pred = helpy.create_random_forest(analysis_df, usage=False)

MAE:  12.184
RMSE: 15.253
R²:   0.253

In [6]:
best_rf, best_pred = helpy.create_random_forest(analysis_df, usage=False, movement=False, movement_residuals=True)

MAE:  12.031
RMSE: 15.144
R²:   0.264

In [7]:
rf, pred = helpy.create_random_forest(analysis_df, usage=False, fip=False)

MAE:  12.903
RMSE: 16.385
R²:   0.138

In [8]:
rf, pred = helpy.create_random_forest(analysis_df, usage=False, movement=False)

MAE:  12.241
RMSE: 15.312
R²:   0.247

In [9]:
rf, pred = helpy.create_random_forest(analysis_df, usage=False, velo=False)

MAE:  12.790
RMSE: 15.619
R²:   0.217

In [10]:
rf, pred = helpy.create_gam(analysis_df, usage=False, movement=False)

MAE:  12.247
RMSE: 15.303
R²:   0.248

In [11]:
rf, pred = helpy.create_gam(analysis_df, usage=False, movement=False)

MAE:  12.247
RMSE: 15.303
R²:   0.248

In [12]:
baseline_gam, baseline_pred = helpy.create_gam(analysis_df, velo=False, movement=False, usage=False)

MAE:  12.750
RMSE: 15.611
R²:   0.218

In [13]:
analysis_df['baseline_pred_fip-'] = baseline_pred
analysis_df['best_pred_fip-'] = best_pred
analysis_df['fip-_diff_best_baseline'] = analysis_df['best_pred_fip-'] - analysis_df['baseline_pred_fip-']

In [14]:
results_df = analysis_df[['PlayerName', 'Season', 'FIP-', 'next_FIP-', 'baseline_pred_fip-', 'best_pred_fip-', 'fip-_diff_best_baseline', 'led_to_breakout']].copy()

In [31]:
results_df.sort_values('fip-_diff_best_baseline')[analysis_df['led_to_breakout']]

/tmp/ipykernel_361568/1433115961.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  results_df.sort_values('fip-_diff_best_baseline')[analysis_df['led_to_breakout']]

,PlayerName,Season,FIP-,next_FIP-,baseline_pred_fip-,best_pred_fip-,fip-_diff_best_baseline,led_to_breakout
2376,Sonny Gray,2016,112.533528,88.967353,107.186189,92.332999,-14.853191,True
2371,Carlos Rodón,2018,115.181181,59.684307,107.769756,92.941419,-14.828337,True
1379,Brad Peacock,2014,131.999153,70.627944,110.773099,96.763703,-14.009397,True
1004,Danny Duffy,2015,112.026956,91.626529,107.071774,93.725274,-13.346501,True
2435,Nathan Eovaldi,2016,112.491482,87.454371,107.176521,93.834900,-13.341621,True
...,...,...,...,...,...,...,...,...
1744,Shohei Ohtani,2021,80.241372,58.788482,90.566860,93.531860,2.965001,True
1762,Tarik Skubal,2022,75.540358,59.584551,86.451154,89.554649,3.103495,True
502,R.A. Dickey,2011,99.720607,83.555098,103.331843,106.542582,3.210738,True
1505,Cristopher Sánchez,2024,72.249694,60.773489,83.588021,88.593292,5.005271,True
1400,Tom Gorzelanny,2008,148.560055,97.216081,98.114926,108.907549,10.792622,True

In [19]:
results_df.sort_values('fip-_diff_best_baseline')[analysis_df['PlayerName'] == 'Danny Duffy']

/tmp/ipykernel_361568/1736665584.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  results_df.sort_values('fip-_diff_best_baseline')[analysis_df['PlayerName'] == 'Danny Duffy']

,PlayerName,Season,FIP-,next_FIP-,baseline_pred_fip-,best_pred_fip-,fip-_diff_best_baseline,led_to_breakout
1004,Danny Duffy,2015,112.026956,91.626529,107.071774,93.725274,-13.346501,True
1754,Danny Duffy,2016,91.626529,80.177667,95.884743,85.213884,-10.670859,True
1221,Danny Duffy,2011,119.813971,102.216498,107.772015,99.410297,-8.361718,False
2245,Danny Duffy,2018,112.768728,106.293937,107.240653,100.853173,-6.387481,False
685,Danny Duffy,2014,102.216498,112.026956,104.698544,99.505853,-5.192691,False
1617,Danny Duffy,2017,80.177667,112.768728,90.523670,95.103376,4.579706,False

In [29]:
top_1_perc = results_df.nsmallest(int(len(results_df) * 0.01), "fip-_diff_best_baseline")
top_5_perc = results_df.nsmallest(int(len(results_df) * 0.05), "fip-_diff_best_baseline")
top_10_perc = results_df.nsmallest(int(len(results_df) * 0.10), "fip-_diff_best_baseline")
top_25_perc = results_df.nsmallest(int(len(results_df) * 0.25), "fip-_diff_best_baseline")
top_50_perc = results_df.nsmallest(int(len(results_df) * 0.50), "fip-_diff_best_baseline")
top_75_perc = results_df.nsmallest(int(len(results_df) * 0.75), "fip-_diff_best_baseline")

In [33]:
print(results_df['led_to_breakout'].mean())
print(top_1_perc['led_to_breakout'].mean())
print(top_5_perc['led_to_breakout'].mean())
print(top_10_perc['led_to_breakout'].mean())
print(top_25_perc['led_to_breakout'].mean())
print(top_50_perc['led_to_breakout'].mean())
print(top_75_perc['led_to_breakout'].mean())

0.1712676056338028
0.8823529411764706
0.7159090909090909
0.6440677966101694
0.4288939051918736
0.30101465614430667
0.22539444027047334