In [2]:
import fungo
from fungo import fangraphs
import pandas as pd

In [3]:
pitchers = fangraphs.get_leaders(stats="pit", start_season=2025, end_season=2025, qual=100, ind=1)

In [4]:
pitchers

[{'Throws': 'L',
  'xMLBAMID': 669373,
  'Name': '<a href="statss.aspx?playerid=22267&position=P">Tarik Skubal</a>',
  'Team': '<a href="leaders.aspx?pos=all&stats=pit&lg=all&qual=0&type=strType&season=2025&month=0&season1=2025&ind=1&team=6&rost=0&age=0">DET</a>',
  'Season': 2025,
  'Age': 28.0,
  'AgeR': '28 - 28',
  'SeasonMin': 2025,
  'SeasonMax': 2025,
  'W': 13.0,
  'L': 6.0,
  'ERA': 2.2116041531508555,
  'G': 31.0,
  'GS': 31.0,
  'QS': 21.0,
  'CG': 1.0,
  'ShO': 1.0,
  'SV': 0.0,
  'BS': 0.0,
  'IP': 195.1,
  'TBF': 748.0,
  'H': 141.0,
  'R': 55.0,
  'ER': 48.0,
  'HR': 18.0,
  'BB': 33.0,
  'IBB': 0.0,
  'HBP': 5.0,
  'WP': 3.0,
  'BK': 2.0,
  'SO': 241.0,
  'GB': 191.0,
  'FB': 179.0,
  'LD': 96.0,
  'IFFB': 21.0,
  'Pitches': 2849.0,
  'Balls': 846.0,
  'Strikes': 2003.0,
  'RS': 100.0,
  'IFH': 14.0,
  'BU': 3.0,
  'BUH': 2.0,
  'K/9': 11.104095852278252,
  'BB/9': 1.520477855291213,
  'K/BB': 7.3030303,
  'H/9': 6.496587199880638,
  'HR/9': 0.8293515574315707,
  'AVG': 0.19859154929577466,
  'WHIP': 0.8907850061302056,
  'BABIP': 0.2727272727272727,
  'LOB%': 0.80624187,
  'FIP': 2.4491294744053644,
  'GB/FB': 1.067039106,
  'LD%': 0.206008583,
  'GB%': 0.409871244,
  'FB%': 0.384120171,
  'IFFB%': 0.117318435,
  'HR/FB': 0.100558659,
  'IFH%': 0.073298429,
  'BUH%': 0.666666666,
  'TTO%': 0.39037433,
  'CFraming': 0.7900000214576721,
  'Starting': 59.66287612915039,
  'Start-IP': 195.10000610351562,
  'Relieving': None,
  'Relief-IP': None,
  'RAR': 59.66287612915039,
  'WAR': 6.70733118057251,
  'Dollars': 53.65864944458008,
  'RA9-Wins': 7.119917392730713,
  'LOB-Wins': -0.060670964419841766,
  'BIP-Wins': 0.4732569754123688,
  'BS-Wins': 0.4125860035419464,
  'tERA': 2.662234778753202,
  'xFIP': 2.663999807721626,
  'WPA': 3.9740383625030518,
  '-WPA': -9.947287559509277,
  '+WPA': 13.921326637268066,
  'RE24': 43.61140060424805,
  'REW': 4.501856803894043,
  'pLI': 0.9464637041091919,
  'inLI': 0.9390994906425476,
  'gmLI': 0.8725806474685669,
  'exLI': 1.2334400415420532,
  'Pulls': 30.0,
  'Games': 31.0,
  'WPA/LI': 5.180756568908691,
  'Clutch': -0.9819285047692414,
  'FB%1': 0.53246753,
  'FBv': 97.49571523,
  'SL%': 0.12495612,
  'SLv': 90.0252809,
  'CT%': None,
  'CTv': None,
  'CB%': 0.02772903,
  'CBv': 81.27848101,
  'CH%': 0.31484731,
  'CHv': 88.09587514,
  'SF%': None,
  'SFv': None,
  'KN%': None,
  'KNv': None,
  'XX%': None,
  'PO%': None,
  'wFB': 13.871475219726562,
  'wSL': 3.984886884689331,
  'wCT': None,
  'wCB': -0.13743510842323303,
  'wCH': 26.27696418762207,
  'wSF': None,
  'wKN': None,
  'wFB/C': 0.9144017943128915,
  'wSL/C': 1.119350248508239,
  'wCT/C': None,
  'wCB/C': -0.17396849167497852,
  'wCH/C': 2.9294274456657825,
  'wSF/C': None,
  'wKN/C': None,
  'O-Swing%': 0.37949762,
  'Z-Swing%': 0.72165698,
  'Swing%': 0.54475254,
  'O-Contact%': 0.54561717,
  'Z-Contact%': 0.78046324,
  'Contact%': 0.69587629,
  'Zone%': 0.48297648,
  'F-Strike%': 0.71524064,
  'SwStr%': 0.16567217,
  'CStr%': 0.15514216,
  'C+SwStr%': 0.32081432,
  'HLD': 0.0,
  'SD': 0.0,
  'MD': 0.0,
  'ERA-': 53.55456759550317,
  'FIP-': 57.16649036768522,
  'xFIP-': 63.01535372347819,
  'K%': 0.32219251,
  'BB%': 0.04411765,
  'K-BB%': 0.27807487,
  'SIERA': 2.713446995385841,
  'kwERA': 2.7086101320338125,
  'RS/9': 4.607508652397615,
  'E-F': -0.23752532125450898,
  'Pull': 174.0,
  'Cent': 162.0,
  'Oppo': 133.0,
  'Soft': 95.0,
  'Med': 240.0,
  'Hard': 134.0,
  'bipCount': 469.0,
  'Pull%': 0.37100213,
  'Cent%': 0.34541578,
  'Oppo%': 0.28358209,
  'Soft%': 0.20255864,
  'Med%': 0.51172708,
  'Hard%': 0.28571429,
  'K/9+': 129.40575334538153,
  'BB/9+': 46.94743652619436,
  'K/BB+': 275.6396549042623,
  'H/9+': 78.2804260330799,
  'HR/9+': 68.8073718362927,
  'AVG+': 82.57653518516037,
  'WHIP+': 69.48520164898372,
  'BABIP+': 95.04778898472796,
  'LOB%+': 110.42074706701706,
  'K%+': 143.1907492698252,
  'BB%+': 51.948530087564926,
  'LD%+': 105.27064320376414,
  'GB%+': 99.12958527995886,
  'FB%+': 98.28177325997612,
  'HRFB%+': 83.69210581093557,
  'Pull%+': 90.24631865479944,
  'Cent%+': 99.38668941648908,
  'Oppo%+': 117.49671863021089,
  'Soft%+': 128.17563551618022,
  'Med%+': 98.40454524948498,
  'Hard%+': 88.74656262547727,
  'xERA': 2.710346836848104,
  'pb_o_CH': 70.90603640223463,
  'pb_s_CH': 67.54290796648044,
  'pb_c_CH': 61.408920245810066,
  'pb_o_CU': 20.0,
  'pb_s_CU': 54.375440000000005,
  'pb_c_CU': 20.0,
  'pb_o_FF': 65.63472997621878,
  'pb_s_FF': 64.59202463733652,
  'pb_c_FF': 57.869302877526756,
  'pb_o_SI': 60.40263595555557,
  'pb_s_SI': 58.683187392592586,
  'pb_c_SI': 64.68189391111112,
  'pb_o_SL': 59.73756303370786,
  'pb_s_SL': 52.79460867977527,
  'pb_c_SL': 61.03104834269664,
  'pb_o_KC': None,
  'pb_s_KC': None,
  'pb_c_KC': None,
  'pb_o_FC': None,
  'pb_s_FC': None,
  'pb_c_FC': None,
  'pb_o_FS': None,
  'pb_s_FS': None,
  'pb_c_FS': None,
  'pb_overall': 68.5132521270621,
  'pb_stuff': 64.83252978588978,
  'pb_command': 63.91299709371709,
  'pb_xRV100': -1.024211804141804,
  'pb_ERA': 2.621210231660231,
  'sp_s_CH': 131.8391284916201,
  'sp_l_CH': 108.17544134078214,
  'sp_p_CH': 137.11349720670393,
  'sp_s_CU': 111.94455696202533,
  'sp_l_CU': 91.34759493670884,
  'sp_p_CU': 95.6073417721519,
  'sp_s_FF': 125.40713436385256,
  'sp_l_FF': 97.12799048751486,
  'sp_p_FF': 118.13800237812124,
  'sp_s_SI': 119.53955555555557,
  'sp_l_SI': 100.43413333333332,
  'sp_p_SI': 122.53685925925922,
  'sp_s_SL': 108.10299435028244,
  'sp_l_SL': 103.25661016949151,
  'sp_p_SL': 114.87694915254235,
  'sp_s_KC': None,
  'sp_l_KC': None,
  'sp_p_KC': None,
  'sp_s_FC': None,
  'sp_l_FC': None,
  'sp_p_FC': None,
  'sp_s_FS': 124.04,
  'sp_l_FS': 151.74,
  'sp_p_FS': 198.17999999999998,
  'sp_s_FO': None,
  'sp_l_FO': None,
  'sp_p_FO': None,
  'sp_stuff': 123.27728242174062,
  'sp_location': 101.76808393532856,
  'sp_pitching': 123.58350189198488,
  'PPTV': 0.0,
  'CPTV': 0.0,
  'BPTV': 0.0,
  'DSV': 0.0,
  'DGV': 0.0,
  'BTV': 0.0,
  'rPPTV': None,
  'rCPTV': None,
  'rBPTV': None,
  'rDSV': None,
  'rDGV': None,
  'rBTV': None,
  'EBV': 0.0,
  'ESV': 0.0,
  'rFTeamV': 0.0,
  'rBTeamV': 0.0,
  'rTV': 0.0,
  'BReview': None,
  'BOverturned': None,
  'BCorrect%': None,
  'wBReview': None,
  'PReview': None,
  'POverturned': None,
  'PCorrect%': None,
  'wPReview': None,
  'CReview': None,
  'COverturned': None,
  'CCorrect%': None,
  'wCReview': None,
  'pfxFA%': 0.2951913,
  'pfxFT%': None,
  'pfxFC%': None,
  'pfxFS%': 0.001053,
  'pfxFO%': None,
  'pfxSI%': 0.23692524,
  'pfxSL%': 0.12495612,
  'pfxCU%': 0.02772903,
  'pfxKC%': None,
  'pfxEP%': None,
  'pfxCH%': 0.31414531,
  'pfxSC%': None,
  'pfxKN%': None,
  'pfxUN%': None,
  'pfxSLO%': 0.12495612,
  'pfxST%': None,
  'pfxCUO%': 0.02772903,
  'pfxCV%': None,
  'pfxvFA': 97.5545760255648,
  'pfxvFT': None,
  'pfxvFC': None,
  'pfxvFS': 89.2999979654948,
  'pfxvFO': None,
  'pfxvSI': 97.29555555555555,
  'pfxvSL': 89.97527870435393,
  'pfxvCU': 81.21265575553798,
  'pfxvKC': None,
  'pfxvEP': None,
  'pfxvCH': 88.04368889664805,
  'pfxvSC': None,
  'pfxvKN': None,
  'pfxvSLO': 89.97527870435393,
  'pfxvST': None,
  'pfxvCUO': 81.21265575553798,
  'pfxvCV': None,
  'pfxFA-X': 2.5126665729971758,
  'pfxFT-X': None,
  'pfxFC-X': None,
  'pfxFS-X': 8.655047098795572,
  'pfxFO-X': None,
  'pfxSI-X': 8.113814380787037,
  'pfxSL-X': -1.2756470240903703,
  'pfxCU-X': -2.420541884023932,
  'pfxKC-X': None,
  'pfxEP-X': None,
  'pfxCH-X': 9.072495853701117,
  'pfxSC-X': None,
  'pfxKN-X': None,
  'pfxSLO-X': -1.2756470240903703,
  'pfxST-X': None,
  'pfxCUO-X': -2.420541884023932,
  'pfxCV-X': None,
  'pfxFA-Z': 10.058897982312724,
  'pfxFT-Z': None,
  'pfxFC-Z': None,
  'pfxFS-Z': 3.9552733103434243,
  'pfxFO-Z': None,
  'pfxSI-Z': 8.159950810185185,
  'pfxSL-Z': 3.029886995808462,
  'pfxCU-Z': -2.8059968586209454,
  'pfxKC-Z': None,
  'pfxEP-Z': None,
  'pfxCH-Z': 4.181371388355447,
  'pfxSC-Z': None,
  'pfxKN-Z': None,
  'pfxSLO-Z': 3.029886995808462,
  'pfxST-Z': None,
  'pfxCUO-Z': -2.8059968586209454,
  'pfxCV-Z': None,
  'pfxwFA': 9.191570281982422,
  'pfxwFT': None,
  'pfxwFC': None,
  'pfxwFS': -0.1787164807319641,
  'pfxwFO': None,
  'pfxwSI': 6.3243608474731445,
  'pfxwSL': 4.108639240264893,
  'pfxwCU': -0.1503734290599823,
  'pfxwKC': None,
  'pfxwEP': None,
  'pfxwCH': 26.75784683227539,
  'pfxwSC': None,
  'pfxwKN': None,
  'pfxwSLO': 4.108639240264893,
  'pfxwST': None,
  'pfxwCUO': -0.1503734290599823,
  'pfxwCV': None,
  'pfxwFA/C': 1.0929334461334628,
  'pfxwFT/C': None,
  'pfxwFC/C': None,
  'pfxwFS/C': -5.957216024398804,
  'pfxwFO/C': None,
  'pfxwSI/C': 0.9369423477737991,
  'pfxwSL/C': 1.1541121461418238,
  'pfxwCU/C': -0.1903461127341548,
  'pfxwKC/C': None,
  'pfxwEP/C': None,
  'pfxwCH/C': 2.9897035566788146,
  'pfxwSC/C': None,
  'pfxwKN/C': None,
  'pfxwSLO/C': 1.1541121461418238,
  'pfxwST/C': None,
  'pfxwCUO/C': -0.1903461127341548,
  'pfxwCV/C': None,
  'pfxaaFA': 52.30578831004756,
  'pfxaaFT': None,
  'pfxaaFC': None,
  'pfxaaFS': 47.73405965169271,
  'pfxaaFO': None,
  'pfxaaSI': 50.028003472222224,
  'pfxaaSL': 49.31567108497191,
  'pfxaaCU': 53.80774080300633,
  'pfxaaKC': None,
  'pfxaaEP': None,
  'pfxaaCH': 46.32195356145252,
  'pfxaaSC': None,
  'pfxaaKN': None,
  'pfxaaSLO': 49.31567108497191,
  'pfxaaST': None,
  'pfxaaCUO': 53.80774080300633,
  'pfxaaCV': None,
  'pfxspFA': 2353.854934601665,
  'pfxspFT': None,
  'pfxspFC': None,
  'pfxspFS': 941.3333333333334,
  'pfxspFO': None,
  'pfxspSI': 2248.5437037037036,
  'pfxspSL': 2232.9129213483147,
  'pfxspCU': 2504.481012658228,
  'pfxspKC': None,
  'pfxspEP': None,
  'pfxspCH': 1837.2983240223464,
  'pfxspSC': None,
  'pfxspKN': None,
  'pfxspSLO': 2232.9129213483147,
  'pfxspST': None,
  'pfxspCUO': 2504.481012658228,
  'pfxspCV': None,
  'pfxO-Swing%': 0.34775767,
  'pfxZ-Swing%': 0.70342205,
  'pfxSwing%': 0.54475254,
  'pfxO-Contact%': 0.47963801,
  'pfxZ-Contact%': 0.78018018,
  'pfxContact%': 0.69458763,
  'pfxZone%': 0.55387855,
  'pfxPace': 17.62619962,
  'AvgBatSpeed': 71.19884935778109,
  'FastSwing%': 0.20997766,
  'SwingLength': 7.260388065431869,
  'SquaredUpContact%': 0.26385809,
  'SquaredUpSwing%': 0.17721519,
  'BlastContact%': 0.09534368,
  'BlastSwing%': 0.06403574,
  'Swords': 27.0,
  'CompetitiveSwings': 1343.0,
  'Tilt': 31.92664510424423,
  'AttackAngle': 9.390531924795235,
  'AttackDirection': -2.6489637748394452,
  'IdealAttackAngle%': 0.44005957,
  'DepthInBox': 26.839805938198065,
  'DistanceOffPlate': 28.08394510889799,
  'scH-Swing%': 0.76595745,
  'scH-Contact%': 0.82309942,
  'scH-Zone%': 0.31344331,
  'scS-Swing%': 0.56934307,
  'scS-Contact%': 0.63817664,
  'scS-Zone%': 0.43278343,
  'scC-Swing%': 0.2833638,
  'scC-Contact%': 0.41290323,
  'scC-Zone%': 0.19199719,
  'scW-Swing%': 0.0625,
  'scW-Contact%': 0.27272727,
  'scW-Zone%': 0.06177606,
  'scSI-Swing%': 0.62462908,
  'scSI-Contact%': 0.6912114,
  'scSI-Zone%': 0.23657424,
  'scSO-Swing%': 0.50268336,
  'scSO-Contact%': 0.55871886,
  'scSO-Zone%': 0.1962092,
  'scO-Swing%': 0.34867395,
  'scO-Contact%': 0.50111857,
  'scO-Zone%': 0.44998245,
  'scZ-Swing%': 0.70516911,
  'scZ-Contact%': 0.77285068,
  'scZ-Zone%': 0.55001755,
  'piCH%': 0.31449631,
  'piCS%': None,
  'piCU%': 0.02843103,
  'piFA%': 0.29378729,
  'piFC%': None,
  'piFS%': None,
  'piKN%': None,
  'piSB%': None,
  'piSI%': 0.23903124,
  'piSL%': 0.12425412,
  'piXX%': None,
  'pivCH': 88.17250279017857,
  'pivCS': None,
  'pivCU': 81.35313585069444,
  'pivFA': 97.70739994026285,
  'pivFC': None,
  'pivFS': None,
  'pivKN': None,
  'pivSB': None,
  'pivSI': 97.43680020190895,
  'pivSL': 90.14782507944915,
  'pivXX': None,
  'piCH-X': 8.690583910260882,
  'piCS-X': None,
  'piCU-X': -2.85396491156684,
  'piFA-X': 2.0279239121303765,
  'piFC-X': None,
  'piFS-X': None,
  'piKN-X': None,
  'piSB-X': None,
  'piSI-X': 7.613471256653818,
  'piSL-X': -1.8417168741172316,
  'piXX-X': None,
  'piCH-Z': 2.6126022338867188,
  'piCS-Z': None,
  'piCU-Z': -4.332709418402778,
  'piFA-Z': 8.929882345803465,
  'piFC-Z': None,
  'piFS-Z': None,
  'piKN-Z': None,
  'piSB-Z': None,
  'piSI-Z': 6.932253665335903,
  'piSL-Z': 1.7828739834370586,
  'piXX-Z': None,
  'piwCH': 26.344228744506836,
  'piwCS': None,
  'piwCU': -0.2039169818162918,
  'piwFA': 9.815632820129395,
  'piwFC': None,
  'piwFS': None,
  'piwKN': None,
  'piwSB': None,
  'piwSI': 5.935200214385986,
  'piwSL': 4.162182807922363,
  'piwXX': None,
  'piwCH/C': 2.9402041009494235,
  'piwCS/C': None,
  'piwCU/C': -0.25174936026702693,
  'piwFA/C': 1.172715988068028,
  'piwFC/C': None,
  'piwFS/C': None,
  'piwKN/C': None,
  'piwSB/C': None,
  'piwSI/C': 0.8715418817013196,
  'piwSL/C': 1.1757578553453003,
  'piwXX/C': None,
  'piO-Swing%': 0.34803528,
  'piZ-Swing%': 0.69787765,
  'piSwing%': 0.54475254,
  'piO-Contact%': 0.48387097,
  'piZ-Contact%': 0.77549195,
  'piContact%': 0.6939433,
  'piZone%': 0.56230256,
  'piPace': 17.62619962,
  'Events': 469.0,
  'EV': 86.1135500672043,
  'LA': 12.70752688172043,
  'Barrels': 38.0,
  'Barrel%': 0.08102345,
  'maxEV': 114.2,
  'HardHit': 155.0,
  'HardHit%': 0.33049041,
  'Q': 1.20576,
  'TG': 162.0,
  'TIP': 195.3333282470703,
  'PlayerNameRoute': 'Tarik Skubal',
  'PlayerName': 'Tarik Skubal',
  'positionDB': 'P',
  'position': 'P',
  'TeamName': 'DET',
  'TeamNameAbb': 'DET',
  'teamid': 6,
  'playerTeamId': 22,
  'playerid': 22267,
  'EV90': 104.1},
 {'Throws': 'R',
  'xMLBAMID': 694973,
  'Name': '<a href="statss.aspx?playerid=33677&position=P">Paul Skenes</a>',
  'Team': '<a href="leaders.aspx?pos=all&stats=pit&lg=all&qual=0&type=strType&season=2025&month=0&season1=2025&ind=1&team=27&rost=0&age=0">PIT</a>',
  'Season': 2025,
  'Age': 23.0,
  'AgeR': '23 - 23',
  'SeasonMin': 2025,
  'SeasonMax': 2025,
  'W': 10.0,
  'L': 10.0,
  'ERA': 1.966252326829945,
  'G': 32.0,
  'GS': 32.0,
  'QS': 20.0,
  'CG': 1.0,
  'ShO': 0.0,
  'SV': 0.0,
  'BS': 0.0,
  'IP': 187.2,
  'TBF': 733.0,
  'H': 136.0,
  'R': 45.0,
  'ER': 41.0,
  'HR': 11.0,
  'BB': 42.0,
  'IBB': 0.0,
  'HBP': 6.0,
  'WP': 2.0,
  'BK': 0.0,
  'SO': 216.0,
  'GB': 207.0,
  'FB': 174.0,
  'LD': 86.0,
  'IFFB': 18.0,
  'Pitches': 2997.0,
  'Balls': 1045.0,
  'Strikes': 1952.0,
  'RS': 71.0,
  'IFH': 17.0,
  'BU': 2.0,
  'BUH': 0.0,
  'K/9': 10.358792746226051,
  'BB/9': 2.0142097006550657,
  'K/BB': 5.14285714,
  'H/9': 6.522202840216402,
  'HR/9': 0.5275311120763266,
  'AVG': 0.19854014598540146,
  'WHIP': 0.9484902823190521,
  'BABIP': 0.27292576419213976,
  'LOB%': 0.82443654,
  'FIP': 2.362489739913177,
  'GB/FB': 1.189655172,
  'LD%': 0.184154175,
  'GB%': 0.443254817,
  'FB%': 0.372591006,
  'IFFB%': 0.103448275,
  'HR/FB': 0.06321839,
  'IFH%': 0.082125603,
  'BUH%': 0.0,
  'TTO%': 0.36698499,
  'CFraming': 0.11999998986721039,
  'Starting': 58.19011306762695,
  'Start-IP': 187.1999969482422,
  'Relieving': None,
  'Relief-IP': None,
  'RAR': 58.19011306762695,
  'WAR': 6.540885925292969,
  'Dollars': 52.32708740234375,
  'RA9-Wins': 8.237894058227539,
  'LOB-Wins': 0.9300680756568909,
  'BIP-Wins': 0.7669402956962585,
  'BS-Wins': 1.6970083713531494,
  'tERA': 2.4844815091083414,
  'xFIP': 3.029963883239011,
  'WPA': 5.183378219604492,
  '-WPA': -9.436397552490234,
  '+WPA': 14.619775772094727,
  'RE24': 52.51750183105469,
  'REW': 5.316885948181152,
  'pLI': 0.9834955930709839,
  'inLI': 0.9765198230743408,
  'gmLI': 0.8729812502861023,
  'exLI': 1.066574215888977,
  'Pulls': 31.0,
  'Games': 32.0,
  'WPA/LI': 4.744187355041504,
  'Clutch': 0.5261750707008366,
  'FB%1': 0.49249249,
  'FBv': 98.10365854,
  'SL%': 0.21488155,
  'SLv': 84.72049689,
  'CT%': None,
  'CTv': None,
  'CB%': 0.04738071,
  'CBv': 83.8943662,
  'CH%': 0.10910911,
  'CHv': 88.78287462,
  'SF%': 0.13613614,
  'SFv': 93.72058824,
  'KN%': None,
  'KNv': None,
  'XX%': None,
  'PO%': None,
  'wFB': 23.762786865234375,
  'wSL': 9.785844802856445,
  'wCT': None,
  'wCB': -4.439892292022705,
  'wCH': 8.362114906311035,
  'wSF': 4.371513366699219,
  'wKN': None,
  'wFB/C': 1.6099449095687244,
  'wSL/C': 1.5195411184559697,
  'wCT/C': None,
  'wCB/C': -3.126684712692046,
  'wCH/C': 2.5572216838871666,
  'wSF/C': 1.0714493545831418,
  'wKN/C': None,
  'O-Swing%': 0.34193548,
  'Z-Swing%': 0.69659443,
  'Swing%': 0.49482816,
  'O-Contact%': 0.58662093,
  'Z-Contact%': 0.80888889,
  'Contact%': 0.72151045,
  'Zone%': 0.43109776,
  'F-Strike%': 0.60845839,
  'SwStr%': 0.13780447,
  'CStr%': 0.15515516,
  'C+SwStr%': 0.29295963,
  'HLD': 0.0,
  'SD': 0.0,
  'MD': 0.0,
  'ERA-': 45.2567813887828,
  'FIP-': 57.85736881400378,
  'xFIP-': 73.74491848953066,
  'K%': 0.2946794,
  'BB%': 0.05729877,
  'K-BB%': 0.23738063,
  'SIERA': 3.096647333859409,
  'kwERA': 3.1969409970599667,
  'RS/9': 3.4049735415835634,
  'E-F': -0.396237413083232,
  'Pull': 202.0,
  'Cent': 167.0,
  'Oppo': 100.0,
  'Soft': 85.0,
  'Med': 246.0,
  'Hard': 138.0,
  'bipCount': 469.0,
  'Pull%': 0.43070362,
  'Cent%': 0.35607676,
  'Oppo%': 0.21321962,
  'Soft%': 0.18123667,
  'Med%': 0.52452026,
  'Hard%': 0.29424307,
  'K/9+': 123.26750766073037,
  'BB/9+': 63.18558982384267,
  'K/BB+': 195.08801538693152,
  'H/9+': 76.96907254111515,
  'HR/9+': 45.64946840748917,
  'AVG+': 81.30117761813726,
  'WHIP+': 73.20126279843608,
  'BABIP+': 93.76000714659675,
  'LOB%+': 115.03740232633734,
  'K%+': 134.32157308235696,
  'BB%+': 68.85177899769944,
  'LD%+': 92.78812814571992,
  'GB%+': 105.15683960332096,
  'FB%+': 98.04644428338513,
  'HRFB%+': 54.02860477739825,
  'Pull%+': 105.3166445422875,
  'Cent%+': 101.7584348272573,
  'Oppo%+': 88.43038691337377,
  'Soft%+': 115.58000925554721,
  'Med%+': 101.18278927601536,
  'Hard%+': 90.59069432832518,
  'xERA': 2.6524270787352653,
  'pb_o_CH': 54.28774168711656,
  'pb_s_CH': 57.3415315030675,
  'pb_c_CH': 54.01770171779142,
  'pb_o_CU': 51.8776345,
  'pb_s_CU': 52.81124364285715,
  'pb_c_CU': 50.23768214285714,
  'pb_o_FF': 60.35196616220736,
  'pb_s_FF': 52.431552290969904,
  'pb_c_FF': 59.02134056856187,
  'pb_o_SI': 60.029612769784165,
  'pb_s_SI': 57.3111879496403,
  'pb_c_SI': 44.29339147482013,
  'pb_o_SL': 66.36752326120555,
  'pb_s_SL': 60.965551885625956,
  'pb_c_SL': 58.310098423493045,
  'pb_o_KC': None,
  'pb_s_KC': None,
  'pb_c_KC': None,
  'pb_o_FC': None,
  'pb_s_FC': None,
  'pb_c_FC': None,
  'pb_o_FS': 62.666338181818176,
  'pb_s_FS': 52.272493812316725,
  'pb_c_FS': 65.85137026392962,
  'pb_overall': 62.35845335669,
  'pb_stuff': 55.868436229562896,
  'pb_command': 58.21391390390391,
  'pb_xRV100': -0.6425749616282952,
  'pb_ERA': 3.193665528862195,
  'sp_s_CH': 99.72104294478527,
  'sp_l_CH': 111.72858895705522,
  'sp_p_CH': 110.54122699386504,
  'sp_s_CU': 110.72319444444445,
  'sp_l_CU': 107.08763888888889,
  'sp_p_CU': 112.80541666666664,
  'sp_s_FF': 106.55377926421406,
  'sp_l_FF': 114.7648829431438,
  'sp_p_FF': 119.60730769230769,
  'sp_s_SI': 113.97283154121862,
  'sp_l_SI': 109.78286738351252,
  'sp_p_SI': 122.66243727598564,
  'sp_s_SL': 128.56046583850932,
  'sp_l_SL': 107.26881987577642,
  'sp_p_SL': 129.64531055900622,
  'sp_s_KC': None,
  'sp_l_KC': None,
  'sp_p_KC': None,
  'sp_s_FC': None,
  'sp_l_FC': None,
  'sp_p_FC': None,
  'sp_s_FS': 96.26425427872863,
  'sp_l_FS': 117.25916870415647,
  'sp_p_FS': 124.57555012224937,
  'sp_s_FO': None,
  'sp_l_FO': None,
  'sp_p_FO': None,
  'sp_stuff': 110.12291917167666,
  'sp_location': 112.05513694054773,
  'sp_pitching': 121.19911155644623,
  'PPTV': 0.0,
  'CPTV': 0.0,
  'BPTV': 0.0,
  'DSV': 0.0,
  'DGV': 0.0,
  'BTV': 0.0,
  'rPPTV': None,
  'rCPTV': None,
  'rBPTV': None,
  'rDSV': None,
  'rDGV': None,
  'rBTV': None,
  'EBV': 0.0,
  'ESV': 0.0,
  'rFTeamV': 0.0,
  'rBTeamV': 0.0,
  'rTV': 0.0,
  'BReview': None,
  'BOverturned': None,
  'BCorrect%': None,
  'wBReview': None,
  'PReview': None,
  'POverturned': None,
  'PCorrect%': None,
  'wPReview': None,
  'CReview': None,
  'COverturned': None,
  'CCorrect%': None,
  'wCReview': None,
  'pfxFA%': 0.39906573,

In [5]:
pitchers_df = pd.DataFrame(pitchers)

In [6]:
pitchers_df

,Throws,xMLBAMID,Name,Team,Season,Age,AgeR,SeasonMin,SeasonMax,W,...,PlayerNameRoute,PlayerName,positionDB,position,TeamName,TeamNameAbb,teamid,playerTeamId,playerid,EV90
0,L,669373,"<a href=""statss.aspx?playerid=22267&position=P...","<a href=""leaders.aspx?pos=all&stats=pit&lg=all...",2025,28.0,28 - 28,2025,2025,13.0,...,Tarik Skubal,Tarik Skubal,P,P,DET,DET,6,22,22267,104.1
1,R,694973,"<a href=""statss.aspx?playerid=33677&position=P...","<a href=""leaders.aspx?pos=all&stats=pit&lg=all...",2025,23.0,23 - 23,2025,2025,10.0,...,Paul Skenes,Paul Skenes,P,P,PIT,PIT,27,27,33677,104.9
2,L,650911,"<a href=""statss.aspx?playerid=20778&position=P...","<a href=""leaders.aspx?pos=all&stats=pit&lg=all...",2025,28.0,28 - 28,2025,2025,13.0,...,Cristopher Sanchez,Cristopher Sánchez,P,P,PHI,PHI,26,26,20778,105.9
3,L,676979,"<a href=""statss.aspx?playerid=27463&position=P...","<a href=""leaders.aspx?pos=all&stats=pit&lg=all...",2025,26.0,26 - 26,2025,2025,18.0,...,Garrett Crochet,Garrett Crochet,P,P,BOS,BOS,3,3,27463,104.8
4,R,657277,"<a href=""statss.aspx?playerid=17995&position=P...","<a href=""leaders.aspx?pos=all&stats=pit&lg=all...",2025,28.0,28 - 28,2025,2025,15.0,...,Logan Webb,Logan Webb,P,P,SFG,SFG,30,30,17995,106.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,R,607200,"<a href=""statss.aspx?playerid=17425&position=P...",- - -,2025,32.0,32 - 32,2025,2025,4.0,...,Erick Fedde,Erick Fedde,P,P,- - -,3 Tms,0,4,17425,104.2
123,L,571760,"<a href=""statss.aspx?playerid=15423&position=P...",- - -,2025,34.0,34 - 34,2025,2025,5.0,...,Andrew Heaney,Andrew Heaney,P,P,- - -,2 Tms,0,-1,15423,105.4
124,R,663623,"<a href=""statss.aspx?playerid=21504&position=P...","<a href=""leaders.aspx?pos=all&stats=pit&lg=all...",2025,28.0,28 - 28,2025,2025,9.0,...,Jake Irvin,Jake Irvin,P,P,WSN,WSN,24,24,21504,104.8
125,R,621111,"<a href=""statss.aspx?playerid=19374&position=P...",- - -,2025,30.0,30 - 30,2025,2025,10.0,...,Walker Buehler,Walker Buehler,P,P,- - -,2 Tms,0,29,19374,105.3
126,R,686799,"<a href=""statss.aspx?playerid=27688&position=P...","<a href=""leaders.aspx?pos=all&stats=pit&lg=all...",2025,24.0,24 - 24,2025,2025,3.0,...,Jack Kochanowicz,Jack Kochanowicz,P,P,LAA,LAA,1,1,27688,105.9

In [11]:
## piwFA = four seam runs above average 
## FC = cutter, FS = splitter, SI = sinker, CH = changeup, SL = slider, CU = curveball

pitchers_df[['PlayerName', 'sp_stuff', 'Season', 'piwFA', 'piwFC', 'piwFS', 'piwSI', 'piwCH', 'piwSL', 'piwCU']]

,PlayerName,sp_stuff,Season,piwFA,piwFC,piwFS,piwSI,piwCH,piwSL,piwCU
0,Tarik Skubal,123.277282,2025,9.815633,NaN,NaN,5.935200,26.344229,4.162183,-0.203917
1,Paul Skenes,110.122919,2025,19.082207,NaN,NaN,9.174253,8.254190,10.254153,-4.929615
2,Cristopher Sánchez,117.576424,2025,NaN,NaN,NaN,19.825800,19.638323,-0.774314,NaN
3,Garrett Crochet,117.010309,2025,-8.827824,8.652262,NaN,13.485263,2.230875,15.765082,NaN
4,Logan Webb,105.813242,2025,0.648588,-3.345829,NaN,8.329859,11.539176,-3.341665,NaN
...,...,...,...,...,...,...,...,...,...,...
122,Erick Fedde,88.509481,2025,0.255742,-8.844628,NaN,-2.900660,-2.297741,2.003235,NaN
123,Andrew Heaney,90.188095,2025,-8.973399,NaN,NaN,1.016920,2.409134,-8.940762,-2.248188
124,Jake Irvin,92.592873,2025,-12.243611,0.879287,NaN,5.350327,-8.722480,1.904243,-11.978921
125,Walker Buehler,96.087697,2025,-7.042878,-4.000706,NaN,5.497813,-3.143609,0.197511,-5.630278
126,Jack Kochanowicz,92.528894,2025,-2.645956,NaN,NaN,-8.483483,-6.421365,-5.435789,-1.577468